

class KeyboardLayout:

    def __init__(self, name: str, replacement_dict: dict):

        self.name = name

        self.replacement_dict = replacement_dict

    def convert_from_qwerty(self, key):

        out = ""
        if self.replacement_dict is None or key not in self.replacement_dict.keys():
            out = key
        else:
            out = self.replacement_dict[key]
        return out


QWERTY = KeyboardLayout('QWERTY', {})
AZERTY = KeyboardLayout('AZERTY', {
        'q': 'a',
        'w': 'z',
        'a': 'q',
        ';': 'm',
        "'": 'ù',
        'z': 'w',
        'm': ',',
        ',': ';',
        '.': ':',
        '/': '!',

        'Q': 'A',
        'W': 'Z',
        'A': "Q",
        ':': "M",
        '"': '%',
        'Z': 'W',
        'M': '?',
        '<': '.',
        '>': '/',
        '?': '§',

    })
QWERTZ = KeyboardLayout('QWERTZ', {
        '`': '^',
        '-': 'ß',
        '=': '`',
        'y': 'z',
        '[': 'ü',
        ']': '+',
        ';': 'ö',
        "'": 'ä',
        'z': 'y',
        '/': '-',

        '@': '"',
        '#': '§',
        '^': '&',
        '&': '/',
        '*': '(',
        '(': ')',
        ')': '=',
        '_': '?',
        '+': '`',
        'Y': 'Z',
        '{': 'Ü',
        '}': '*',
        ':': 'Ö',
        '"': 'Ä',
        'Z': 'Y',
        '?': '_',

    })
DVORAK = KeyboardLayout('Dvorak', {
        '-': '[',
        '=': ']',
        'q': "'",
        'w': ',',
        'e': '.',
        'r': 'p',
        't': 'y',
        'y': 'f',
        'u': 'g',
        'i': 'c',
        'o': 'r',
        'p': 'l',
        '[': '/',
        ']': '=',
        'a': 'a',
        's': 'o',
        'd': 'e',
        'f': 'u',
        'g': 'i',
        'h': 'd',
        'j': 'h',
        'k': 't',
        'l': 'n',
        ';': 's',
        "'": '-',
        'z': ';',
        'x': 'q',
        'c': 'j',
        'v': 'k',
        'b': 'x',
        'n': 'b',
        'm': 'm',
        ',': 'w',
        '.': 'v',
        '/': 'z',
        'Q': '"',
        'W': '<',
        'E': '>',
        'R': 'P',
        'T': 'Y',
        'Y': 'F',
        'U': 'G',
        'I': 'C',
        'O': 'R',
        'P': 'L',
        '{': '?',
        '}': '+',
        'A': 'A',
        'S': 'O',
        'D': 'E',
        'F': 'U',
        'G': 'I',
        'H': 'D',
        'J': 'H',
        'K': 'T',
        'L': 'N',
        ':': 'S',
        '"': '_',
        'Z': ':',
        'X': 'Q',
        'C': 'J',
        'V': 'K',
        'B': 'X',
        'N': 'B',
        'M': 'M',
        '<': 'W',
        '>': 'V',
        '?': 'Z',
    })
COLEMAK = KeyboardLayout('Colemak', {
        'e': 'f',
        'r': 'p',
        't': 'g',
        'y': 'j',
        'u': 'l',
        'i': 'u',
        'o': 'y',
        'p': ';',
        's': 'r',
        'd': 's',
        'f': 't',
        'g': 'd',
        'h': 'h',
        'j': 'n',
        'k': 'e',
        'l': 'i',
        ';': 'o',
        'z': 'z',
        'x': 'x',
        'c': 'c',
        'v': 'v',
        'b': 'b',
        'n': 'k',
        'm': 'm',

        'E': 'F',
        'R': 'P',
        'T': 'G',
        'Y': 'J',
        'U': 'L',
        'I': 'U',
        'O': 'Y',
        'P': ':',
        'S': 'R',
        'D': 'S',
        'F': 'T',
        'G': 'D',
        'H': 'H',
        'J': 'N',
        'K': 'E',
        'L': 'I',
        ':': 'O',
        'Z': 'Z',
        'X': 'X',
        'C': 'C',
        'V': 'V',
        'B': 'B',
        'N': 'K',
        'M': 'M',
    })
WORKMAN = KeyboardLayout('Workman', {
        'q': "q",
        'w': 'd',
        'e': 'r',
        'r': 'w',
        't': 'b',
        'y': 'j',
        'u': 'f',
        'i': 'u',
        'o': 'p',
        'p': ';',
        'a': 'a',
        's': 's',
        'd': 'h',
        'f': 't',
        'g': 'g',
        'h': 'y',
        'j': 'n',
        'k': 'e',
        'l': 'o',
        ';': 'i',
        'z': 'z',
        'x': 'x',
        'c': 'm',
        'v': 'c',
        'b': 'v',
        'n': 'k',
        'm': 'l',

        'Q': 'Q',
        'W': 'D',
        'E': 'R',
        'R': 'W',
        'T': 'B',
        'Y': 'J',
        'U': 'F',
        'I': 'U',
        'O': 'P',
        'P': ':',
        'A': 'A',
        'S': 'S',
        'D': 'H',
        'F': 'T',
        'G': 'G',
        'H': 'Y',
        'J': 'N',
        'K': 'E',
        'L': 'O',
        ':': 'I',
        'Z': 'Z',
        'X': 'X',
        'C': 'M',
        'V': 'C',
        'B': 'V',
        'N': 'K',
        'M': 'L',
    })
NEO2 = KeyboardLayout('Neo', {
        # Ref: https://www.neo-layout.org/Layouts/neo/
        'q': "x",
        'w': 'v',
        'e': 'l',
        'r': 'c',
        't': 'w',
        'y': 'k',
        'u': 'h',
        'i': 'g',
        'o': 'f',
        'p': 'q',
        '[': 'ß',

        'a': 'u',
        's': 'i',
        'd': 'a',
        'f': 'e',
        'g': 'o',
        'h': 's',
        'j': 'n',
        'k': 'r',
        'l': 't',
        ';': 'd',
        "'": 'y',

        'z': 'ü',
        'x': 'ö',
        'c': 'ä',
        'v': 'p',
        'b': 'z',
        'n': 'b',
        'm': 'm',
        '/': 'j',

        '!': '°',
        '@': '§',
        # Todo: The rest of these. We can get away with not filling these in for now because none of the shortcuts use them.

        'Q': 'X',
        'W': 'V',
        'E': 'L',
        'R': 'C',
        'T': 'W',
        'Y': 'K',
        'U': 'H',
        'I': 'G',
        'O': 'F',
        'P': 'Q',
        '{': 'ẞ',

        'A': 'U',
        'S': 'I',
        'D': 'A',
        'F': 'E',
        'G': 'O',
        'H': 'S',
        'J': 'N',
        'K': 'R',
        'L': 'T',
        ':': 'D',
        '"': 'Y',

        'Z': 'Ü',
        'X': 'Ö',
        'C': 'Ä',
        'V': 'P',
        'B': 'Z',
        'N': 'B',
        'M': 'M',
        '<': '-',
        # '>': '' TODO this is like a dot or a bullet?
        '?': 'J',
    })
layouts = [
        QWERTY,
        QWERTZ,
        AZERTY,
        DVORAK,
        COLEMAK,
        WORKMAN,
        NEO2,
]